name: Java CI with docker and GitHub S

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml 
        
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: Swetha2830/new-hello-world-springboot-app-v2
        tag: v5
        registry: ghcr.io        
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
